
murmur_test_SOURCES := murmur_test.c
murmur_test_ADDLIBS := ../lib/libpotato.so
murmur_test_CPPFLAGS := -I ../lib
murmur_test_LDFLAGS := -pthread -lpthread


threadPool_0_SOURCES := threadPool_0.c
threadPool_0_ADDLIBS := ../lib/libpotato.so
threadPool_0_CPPFLAGS := -I ../lib
threadPool_0_LDFLAGS := -pthread -lpthread



include ../quickbuild.make
