CPPFLAGS := -I ../lib
LDFLAGS := -pthread -lpthread
CFLAGS := -Wall -Werror


murmur_test_SOURCES := murmur_test.c
murmur_test_ADDLIBS := ../lib/libpotato.so


threadPool_sleep_SOURCES := threadPool_sleep.c
threadPool_sleep_ADDLIBS := ../lib/libpotato.so



include ../quickbuild.make
