CPPFLAGS := -I ../lib
LDFLAGS := -pthread -lpthread
ADDLIBS := ../lib/libpotato.so


murmur_test_SOURCES := murmur_test.c

threadPool_sleep_SOURCES := threadPool_sleep.c

threadPool_tryDestroy_SOURCES := threadPool_tryDestroy.c

threadPool_checkIdle_SOURCES := threadPool_checkIdle.c

threadPool_runTaskTimeout_SOURCES := threadPool_runTaskTimeout.c




include ../quickbuild.make
